name: Docker Image CI

on:
  workflow_dispatch:  # 只允许手动触发

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            darkathena/plsqlrewrite4gaussdb-web:latest
            darkathena/plsqlrewrite4gaussdb-web:${{ github.sha }}
